# Generated by Django 6.0.5 on 2026-06-05 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performance', '0013_add_uplift_and_competency_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOMCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('open', 'Open — Nominations Accepted'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EOMNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('hr_finalized', 'HR Finalized')], default='draft', max_length=30)),
                ('manager_remarks', models.TextField(blank=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_remarks', models.TextField(blank=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('hr_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='eom.eomcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eom_nominations', to='performance.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
    ]
