# Generated by Django 6.0.5 on 2026-06-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eom', '0010_nomination_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='eomemployee',
            name='is_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eomemployee',
            name='is_panel_member',
            field=models.BooleanField(default=False),
        ),
    ]
