# Generated by Django 6.0.5 on 2026-06-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eom', '0011_add_is_panel_member_is_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eomemployee',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee — Can fill form'), ('hod', 'HOD Only — Reviews HOD section'), ('panel', 'Panel Only — Reviews Panel sections'), ('hod+panel', 'HOD + Panel — Reviews both sections'), ('hr', 'HR Admin — Manages & finalizes')], default='employee', max_length=20),
        ),
    ]
