# Generated by Django 6.0.5 on 2026-06-22 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eom', '0012_update_user_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOMActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('nomination_created', 'Nomination Created'), ('nomination_submitted', 'Nomination Submitted by Employee'), ('hod_reviewed', 'HOD Review Completed'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('panel_reviewed', 'Panel Review Completed'), ('panel_approved', 'Panel Approved'), ('panel_rejected', 'Panel Rejected'), ('hr_finalized', 'HR Finalized'), ('winner_declared', 'Winner Declared'), ('panel_member_assigned', 'Panel Member Assigned'), ('panel_member_removed', 'Panel Member Removed')], max_length=50)),
                ('actor_role', models.CharField(max_length=20)),
                ('actor_name', models.CharField(max_length=200)),
                ('actor_id', models.CharField(blank=True, max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='eom.eomcycle')),
                ('nomination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='eom.eomnomination')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['nomination', '-timestamp'], name='eom_eomacti_nominat_ec9c9c_idx'), models.Index(fields=['cycle', '-timestamp'], name='eom_eomacti_cycle_i_d4cd91_idx')],
            },
        ),
    ]
