# Generated by Django 5.2.17 on 2026-10-06 08:15

import django.db.models.deletion
import policies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_backfill_can_manage_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('submitted_by_name', models.CharField(blank=True, max_length=200)),
                ('submitted_by_email', models.CharField(blank=True, max_length=254)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SOP', 'SOP'), ('Manual Policy', 'Manual Policy'), ('Templates', 'Templates'), ('Work Instructions', 'Work Instructions'), ('Formats', 'Formats')], max_length=40)),
                ('department', models.CharField(blank=True, max_length=60)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('doc_approved_by', models.CharField(blank=True, max_length=200)),
                ('doc_reviewed_by', models.CharField(blank=True, max_length=200)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to=policies.models.document_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviews', to='accounts.portaluser')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submissions', to='accounts.portaluser')),
            ],
            options={
                'verbose_name': 'policy document',
                'ordering': ['-created_at'],
            },
        ),
    ]
