# Generated by Django 5.2.17 on 2026-10-06 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_backfill_can_manage_tree'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltInRemoval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('removed_by_name', models.CharField(blank=True, max_length=200)),
                ('removed_at', models.DateTimeField(auto_now_add=True)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.portaluser')),
            ],
            options={
                'verbose_name': 'removed built-in policy',
                'ordering': ['-removed_at'],
            },
        ),
    ]
