# Generated by Django 6.0.5 on 2026-08-13 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TadaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(blank=True, max_length=10)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('hq_city', models.CharField(blank=True, max_length=200)),
                ('reporting_manager_id', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR'), ('finance', 'Finance'), ('admin', 'Admin')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_rc_no', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TadaOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='tada.tadauser')),
            ],
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('tour_sanction', 'Tour Programme Sanction'), ('travel_expense', 'Travelling Expenses'), ('local_travel', 'Local Travel')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted · Pending Manager'), ('manager_approved', 'Manager Approved · Pending HR'), ('manager_rejected', 'Rejected by Manager'), ('hr_approved', 'HR Approved · Pending Finance'), ('hr_rejected', 'Rejected by HR'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Rejected by Finance'), ('paid', 'Paid / Settled')], default='draft', max_length=25)),
                ('purpose', models.TextField(blank=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('travel_address', models.CharField(blank=True, max_length=500)),
                ('destination_city', models.CharField(blank=True, max_length=200)),
                ('city_grade', models.CharField(blank=True, max_length=1)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('sanction_number', models.CharField(blank=True, max_length=100)),
                ('estimate_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travel_mode', models.CharField(blank=True, max_length=100)),
                ('local_travel_type', models.CharField(blank=True, max_length=100)),
                ('total_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('finance_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_action_at', models.DateTimeField(blank=True, null=True)),
                ('hr_action_at', models.DateTimeField(blank=True, null=True)),
                ('finance_action_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tada.tadauser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalTravelItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=300)),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('policy_flag', models.CharField(blank=True, max_length=400)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_items', to='tada.travelrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('travel', 'Travel Details'), ('lodging', 'Lodging'), ('food', 'Food / DA'), ('local_transport', 'Local Transport'), ('misc', 'Miscellaneous')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('from_location', models.CharField(blank=True, max_length=200)),
                ('to_location', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bill', models.FileField(blank=True, null=True, upload_to='tada_bills/')),
                ('gst_verified', models.BooleanField(default=False)),
                ('policy_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('policy_flag', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='tada.travelrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=20)),
                ('by_name', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tada.travelrequest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
