# Generated by Django 6.0.5 on 2026-08-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='travel_mode_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='travel_mode_time_pref',
            field=models.CharField(blank=True, choices=[('early_morning', 'Early Morning (12 AM – 6 AM)'), ('morning', 'Morning (6 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 4 PM)'), ('evening', 'Evening (4 PM – 8 PM)'), ('night', 'Night (8 PM – 12 AM)')], max_length=20),
        ),
    ]
