# Generated by Django 6.0.5 on 2026-08-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0003_travelrequest_return_mode_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='est_food_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='est_local_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='est_lodging_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='est_misc_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='est_ticket_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='policy_flags',
            field=models.TextField(blank=True),
        ),
    ]
