# Generated by Django 6.0.5 on 2026-08-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0004_travelrequest_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='mode_exception_reason',
            field=models.TextField(blank=True),
        ),
    ]
