# Generated by Django 6.0.5 on 2026-08-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0005_travelrequest_mode_exception_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=0)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('destination_city', models.CharField(blank=True, max_length=200)),
                ('city_grade', models.CharField(blank=True, max_length=1)),
                ('purpose', models.CharField(blank=True, max_length=500)),
                ('travel_mode', models.CharField(blank=True, max_length=100)),
                ('ticket_date', models.DateField(blank=True, null=True)),
                ('ticket_time_pref', models.CharField(blank=True, choices=[('early_morning', 'Early Morning (12 AM – 6 AM)'), ('morning', 'Morning (6 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 4 PM)'), ('evening', 'Evening (4 PM – 8 PM)'), ('night', 'Night (8 PM – 12 AM)')], max_length=20)),
                ('mode_exception_reason', models.TextField(blank=True)),
                ('est_ticket_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_lodging_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_food_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('est_local_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='tada.travelrequest')),
            ],
            options={
                'ordering': ['seq', 'from_date'],
            },
        ),
    ]
