# Generated by Django 6.0.5 on 2026-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0006_travelleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelleg',
            name='travel_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
