# Generated by Django 6.0.5 on 2026-08-21 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0007_travelleg_travel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='sanction',
            field=models.ForeignKey(blank=True, limit_choices_to={'request_type': 'tour_sanction'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='tada.travelrequest'),
        ),
    ]
