# Generated by Django 6.0.5 on 2026-08-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0008_travelrequest_sanction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='tada.travelleg'),
        ),
    ]
