# Generated by Django 6.0.5 on 2026-08-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0009_expenseitem_leg'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallog',
            name='advance_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='briefing',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='deviation_justification',
            field=models.TextField(blank=True),
        ),
    ]
