# Generated by Django 6.0.5 on 2026-08-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0010_approvallog_advance_remarks_approvallog_briefing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='vendor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
