# Generated by Django 6.0.5 on 2026-08-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0011_expenseitem_check_in_expenseitem_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='cap_basis',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='cap_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
