# Generated by Django 6.0.5 on 2026-08-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0012_expenseitem_cap_basis_expenseitem_cap_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelleg',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelleg',
            name='booked_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelleg',
            name='booking_carrier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelleg',
            name='booking_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelleg',
            name='booking_mode',
            field=models.CharField(choices=[('self', 'Booked by me — I will claim the fare'), ('company', 'Booked by the company — Travel Help Desk')], default='self', max_length=10),
        ),
        migrations.AddField(
            model_name='travelleg',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelleg',
            name='booking_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelleg',
            name='booking_status',
            field=models.CharField(choices=[('not_required', 'Self-booked — nothing for the desk'), ('pending', 'Awaiting booking by the Travel Help Desk'), ('booked', 'Booked'), ('cancelled', 'Booking cancelled')], default='not_required', max_length=15),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booked_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booking_carrier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booking_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booking_mode',
            field=models.CharField(choices=[('self', 'Booked by me — I will claim the fare'), ('company', 'Booked by the company — Travel Help Desk')], default='self', max_length=10),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booking_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booking_status',
            field=models.CharField(choices=[('not_required', 'Self-booked — nothing for the desk'), ('pending', 'Awaiting booking by the Travel Help Desk'), ('booked', 'Booked'), ('cancelled', 'Booking cancelled')], default='not_required', max_length=15),
        ),
        migrations.AlterField(
            model_name='tadauser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR'), ('finance', 'Finance'), ('travel_desk', 'Travel Help Desk'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
