# Generated by Django 6.0.5 on 2026-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0013_travelleg_booked_at_travelleg_booked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvallog',
            name='tour_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tadauser',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'P&C (HR)'), ('finance', 'Finance'), ('travel_desk', 'Travel Help Desk'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted · Pending Manager'), ('manager_approved', 'Manager Approved · Pending P&C (HR)'), ('manager_rejected', 'Rejected by Manager'), ('hr_approved', 'P&C (HR) Approved · Pending Finance'), ('hr_rejected', 'Rejected by P&C (HR)'), ('finance_approved', 'Finance Approved'), ('finance_rejected', 'Rejected by Finance'), ('paid', 'Paid / Settled')], default='draft', max_length=25),
        ),
    ]
