# Generated by Django 6.0.5 on 2026-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0014_approvallog_tour_justification_alter_tadauser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='return_booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_booked_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_booking_carrier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_booking_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_booking_mode',
            field=models.CharField(choices=[('self', 'Booked by me — I will claim the fare'), ('company', 'Booked by the company — Travel Help Desk')], default='self', max_length=10),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_booking_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_booking_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_booking_status',
            field=models.CharField(choices=[('not_required', 'Self-booked — nothing for the desk'), ('pending', 'Awaiting booking by the Travel Help Desk'), ('booked', 'Booked'), ('cancelled', 'Booking cancelled')], default='not_required', max_length=15),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_travel_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='traveller_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='traveller_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='trip_type',
            field=models.CharField(choices=[('round_trip', 'To & Fro'), ('one_way', 'One Way')], default='round_trip', max_length=12),
        ),
    ]
