# Generated by Django 6.0.5 on 2026-08-26 05:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0015_travelrequest_return_booked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelleg',
            name='booking_ticket',
            field=models.FileField(blank=True, null=True, upload_to='tada_tickets/'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='booking_ticket',
            field=models.FileField(blank=True, null=True, upload_to='tada_tickets/'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_booking_ticket',
            field=models.FileField(blank=True, null=True, upload_to='tada_tickets/'),
        ),
        migrations.AlterField(
            model_name='travelleg',
            name='booking_status',
            field=models.CharField(choices=[('not_required', 'Self-booked — nothing for the desk'), ('pending', 'Awaiting booking by the Travel Help Desk'), ('options_sent', "Options sent — awaiting the employee's choice"), ('confirmed', 'Employee has chosen — awaiting ticketing'), ('booked', 'Booked'), ('cancelled', 'Booking cancelled')], default='not_required', max_length=15),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='booking_status',
            field=models.CharField(choices=[('not_required', 'Self-booked — nothing for the desk'), ('pending', 'Awaiting booking by the Travel Help Desk'), ('options_sent', "Options sent — awaiting the employee's choice"), ('confirmed', 'Employee has chosen — awaiting ticketing'), ('booked', 'Booked'), ('cancelled', 'Booking cancelled')], default='not_required', max_length=15),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='return_booking_status',
            field=models.CharField(choices=[('not_required', 'Self-booked — nothing for the desk'), ('pending', 'Awaiting booking by the Travel Help Desk'), ('options_sent', "Options sent — awaiting the employee's choice"), ('confirmed', 'Employee has chosen — awaiting ticketing'), ('booked', 'Booked'), ('cancelled', 'Booking cancelled')], default='not_required', max_length=15),
        ),
        migrations.CreateModel(
            name='BookingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_key', models.CharField(max_length=20)),
                ('seq', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(blank=True, max_length=200)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('added_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_options', to='tada.travelrequest')),
            ],
            options={
                'ordering': ['journey_key', 'seq'],
            },
        ),
    ]
