# Generated by Django 6.0.5 on 2026-08-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0016_travelleg_booking_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelleg',
            name='from_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='from_city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
