# Generated by Django 6.0.5 on 2026-08-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tada', '0017_travelleg_from_city_travelrequest_from_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='StayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=0)),
                ('leg_seq', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=300)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='tada.travelrequest')),
            ],
            options={
                'ordering': ['seq', 'check_in'],
            },
        ),
    ]
