# Generated by Django 5.2.17 on 2026-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('position_applied_for', models.CharField(max_length=250)),
                ('candidate_department', models.CharField(blank=True, max_length=100)),
                ('candidate_employee_id', models.CharField(blank=True, max_length=50)),
                ('candidate_contact', models.CharField(blank=True, max_length=30)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('referrer_name', models.CharField(max_length=200)),
                ('referrer_employee_id', models.CharField(blank=True, max_length=50)),
                ('referrer_designation', models.CharField(blank=True, max_length=150)),
                ('referrer_department', models.CharField(blank=True, max_length=100)),
                ('referrer_contact', models.CharField(blank=True, max_length=30)),
                ('referrer_email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('relationship_other', models.CharField(blank=True, max_length=200)),
                ('association_duration', models.CharField(blank=True, max_length=100)),
                ('previous_organization', models.CharField(blank=True, max_length=200)),
                ('candidate_previous_designation', models.CharField(blank=True, max_length=150)),
                ('employment_from', models.DateField(blank=True, null=True)),
                ('employment_to', models.DateField(blank=True, null=True)),
                ('reporting_to', models.CharField(blank=True, max_length=150)),
                ('technical_skills', models.CharField(blank=True, max_length=300)),
                ('strengths', models.CharField(blank=True, max_length=300)),
                ('areas_of_improvement', models.CharField(blank=True, max_length=300)),
                ('overall_performance', models.CharField(blank=True, max_length=50)),
                ('recommendation', models.CharField(choices=[('strong', 'Strongly Recommend'), ('recommend', 'Recommend'), ('reservations', 'Recommend with Reservations'), ('not', 'Do Not Recommend')], max_length=20)),
                ('disciplinary_issues', models.BooleanField(default=False)),
                ('disciplinary_details', models.TextField(blank=True)),
                ('referrer_signature', models.CharField(blank=True, max_length=200)),
                ('declaration_date', models.DateField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=150)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Interviewing', 'Interviewing'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
