# Generated by Django 6.0.5 on 2026-06-19 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fiscal_year', models.CharField(default='2025-26', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMSEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('band', models.CharField(blank=True, choices=[('D', 'Director Band'), ('C', 'CXO / HOD / Leader'), ('M', 'Middle Management'), ('O', 'Officer / Supervisor'), ('W', 'Workforce / Associate')], max_length=5)),
                ('current_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('manager_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hod_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('management_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hod_remarks', models.TextField(blank=True)),
                ('override_increment_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('override_grade', models.CharField(blank=True, max_length=5)),
                ('promoted', models.BooleanField(default=False)),
                ('on_time_reward', models.BooleanField(default=False)),
                ('management_discretion', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pms.pmssession')),
            ],
            options={
                'ordering': ['department', 'name'],
                'unique_together': {('session', 'employee_id')},
            },
        ),
    ]
