# Generated by Django 6.0.5 on 2026-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pmsemployee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fiscal_year',
            field=models.CharField(blank=True, default='2025-26', max_length=20),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_prev1_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_prev2_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='promotion_readiness',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pmsemployee',
            name='current_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pmsemployee',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='pmsemployee',
            name='session',
        ),
        migrations.DeleteModel(
            name='PMSSession',
        ),
    ]
