# Generated by Django 6.0.5 on 2026-06-19 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_simplify_no_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmsemployee',
            name='fy_prev1_score',
        ),
        migrations.RemoveField(
            model_name='pmsemployee',
            name='fy_prev2_score',
        ),
        migrations.RemoveField(
            model_name='pmsemployee',
            name='management_discretion',
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='business',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='cadre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_prev1_grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_prev2_grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='management_discretion_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='promotion_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pmsemployee',
            name='band',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pmsemployee',
            name='current_ctc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='PMSAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, default='HR Admin', max_length=200)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pms.pmsemployee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
