# Generated by Django 6.0.5 on 2026-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_add_cadre_business_promotion_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmsemployee',
            name='fy_prev1_grade',
        ),
        migrations.RemoveField(
            model_name='pmsemployee',
            name='fy_prev2_grade',
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='cost_centre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2223_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2223_grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2223_growth_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2324_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2324_grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2324_growth_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2425_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2425_grade',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='fy_2425_growth_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='hod_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='hod_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='hq_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='last_promotion_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='new_designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='new_designation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='new_operational_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='payroll_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='redesignation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='reporting_manager',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='reporting_manager_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='salary_correction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='self_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='span_of_control',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmsemployee',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
