# Generated by Django 6.0.5 on 2026-07-08 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_add_span_of_control'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmsemployee',
            name='span_of_control',
        ),
    ]
