# Generated by Django 6.0.5 on 2026-07-24 05:16
# Trimmed to only add the two new OfferLetter fields (the auto-generated
# AlterField id -> BigAutoField ops were removed; they are unrelated to this
# change and must not touch id columns on tables that already hold data).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_sustained_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='assessment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='offerletter',
            name='salutation',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
