# Generated by Django 6.0.5 on 2026-07-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0017_pmsemployee_variable_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='performance_rating',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
