# Generated by Django 6.0.5 on 2026-08-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0018_widen_performance_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningLetterBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('generated', models.IntegerField(default=0)),
                ('emailed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('send_emails', models.BooleanField(default=False)),
                ('status', models.CharField(default='running', max_length=20)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # NOTE: makemigrations also auto-detects unrelated `id` -> BigAutoField
        # alterations on offerletter/pmssettings (a pre-existing DEFAULT_AUTO_FIELD
        # config gap). They are deliberately NOT included here — this migration
        # must only create the two new warning-letter tables and must not touch
        # the live appraisal tables in PROD.
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=50)),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('salutation', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, db_index=True, max_length=200)),
                ('function', models.CharField(blank=True, max_length=200)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('cadre', models.CharField(blank=True, max_length=100)),
                ('date_of_joining', models.CharField(blank=True, max_length=50)),
                ('work_location', models.CharField(blank=True, max_length=200)),
                ('reporting_manager', models.CharField(blank=True, max_length=200)),
                ('warning_type', models.CharField(choices=[('verbal', 'Verbal Warning'), ('first', 'First Written Warning'), ('second', 'Second Written Warning'), ('final', 'Final Warning'), ('show_cause', 'Show Cause Notice')], default='first', max_length=20)),
                ('warning_type_label', models.CharField(blank=True, max_length=150)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('incident_date', models.CharField(blank=True, max_length=50)),
                ('incident_description', models.TextField(blank=True)),
                ('previous_warning_ref', models.CharField(blank=True, max_length=300)),
                ('corrective_action', models.TextField(blank=True)),
                ('response_due_days', models.IntegerField(default=0)),
                ('letter_date', models.DateField()),
                ('issued_by', models.CharField(blank=True, max_length=200)),
                ('issued_by_designation', models.CharField(blank=True, max_length=300)),
                ('remarks', models.TextField(blank=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='warning_letters/')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('cc_emails', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_letters', to='pms.pmsemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
