# Generated by Django 6.0.5 on 2026-09-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_warning_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerletter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pmssettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
