# Generated by Django 6.0.5 on 2026-09-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_warning_letters'),
    ]

    operations = [
        # The two "alter id to BigAutoField" operations Django wants here are
        # deliberately left out. They cannot run on MySQL - pms_offerletterapproval
        # is an orphan table holding an int FK into pms_offerletter.id, so widening
        # the target leaves an incompatible constraint and migrate dies mid-deploy.
        # Cosmetic either way; reverted once already. Leave them out.

        migrations.CreateModel(
            name='ArrearsLetter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('employee_name', models.CharField(blank=True, max_length=200)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, db_index=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('cadre', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100)),
                ('paid_days', models.CharField(blank=True, max_length=50)),
                ('period', models.CharField(blank=True, max_length=120)),
                ('salary_breakup', models.JSONField(blank=True, default=dict)),
                ('totals', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='arrears_letters/')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('batch_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArrearsLetterBatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('generated', models.IntegerField(default=0)),
                ('emailed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('send_emails', models.BooleanField(default=False)),
                ('status', models.CharField(default='running', max_length=20)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
