# Generated by Django 6.0.5 on 2026-05-19 05:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('subzone', models.CharField(blank=True, max_length=100)),
                ('reporting_manager_id', models.CharField(blank=True, max_length=50)),
                ('user_type', models.CharField(choices=[('field_force', 'Field Force'), ('manager', 'Manager'), ('hr', 'HR Admin')], default='field_force', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('hr_approved', 'HR Approved'), ('finalized', 'Finalized')], default='draft', max_length=30)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_cards', to='performance.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sales', '💰 Sales & Revenue'), ('customer', '🤝 Customer Relations'), ('learning', '📚 Learning & Growth'), ('process', '⚙️ Process Excellence'), ('innovation', '🚀 Innovation & Initiatives')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kpi_metric', models.CharField(blank=True, max_length=200)),
                ('target_value', models.CharField(blank=True, max_length=200)),
                ('weightage', models.IntegerField(default=20)),
                ('self_completion_pct', models.IntegerField(blank=True, null=True)),
                ('self_rating', models.IntegerField(blank=True, null=True)),
                ('self_comments', models.TextField(blank=True)),
                ('achievement_description', models.TextField(blank=True)),
                ('manager_rating', models.IntegerField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('hr_rating', models.IntegerField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.IntegerField(default=0)),
                ('goal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.goalcard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=20)),
                ('actor_name', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='performance.goalcard')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('fiscal_year', models.CharField(max_length=10)),
                ('goal_setting_deadline', models.DateField()),
                ('review_start_date', models.DateField()),
                ('review_deadline', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('goal_setting', 'Goal Setting Open'), ('goals_locked', 'Goals Locked'), ('review_open', 'Review Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fiscal_year', 'quarter'],
                'unique_together': {('quarter', 'fiscal_year')},
            },
        ),
        migrations.AddField(
            model_name='goalcard',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_cards', to='performance.performancecycle'),
        ),
        migrations.CreateModel(
            name='QuarterlyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='performance/evidence/')),
                ('employee_summary', models.TextField(blank=True)),
                ('key_achievements', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('next_quarter_plans', models.TextField(blank=True)),
                ('overall_self_rating', models.IntegerField(blank=True, null=True)),
                ('manager_overall_rating', models.IntegerField(blank=True, null=True)),
                ('manager_review_comments', models.TextField(blank=True)),
                ('hr_final_rating', models.IntegerField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('final_weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('performance_band', models.CharField(blank=True, choices=[('outstanding', '🏆 Outstanding'), ('exceeds', '⭐ Exceeds Expectations'), ('meets', '✅ Meets Expectations'), ('below', '⚠️ Below Expectations'), ('poor', '❌ Needs Improvement')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted'), ('manager_reviewed', 'Manager Reviewed'), ('hr_finalized', 'HR Finalized'), ('published', 'Published')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('goal_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='performance.goalcard')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='goalcard',
            unique_together={('employee', 'cycle')},
        ),
    ]
