# Generated by Django 6.0.5 on 2026-05-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_pct', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('ahead', 'Ahead of Schedule'), ('at_risk', 'At Risk'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='on_track', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='performance.goal')),
            ],
            options={
                'ordering': ['-update_date', '-created_at'],
            },
        ),
    ]
