# Generated by Django 6.0.5 on 2026-05-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlyreview',
            name='areas_of_improvement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='career_aspirations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='development_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='employee_strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='functional_head_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='functional_head_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='increment_recommendation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='management_approval_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='management_approval_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='promotion_recommendation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='support_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quarterlyreview',
            name='training_needs',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(choices=[('ownership', 'Ownership & Accountability'), ('communication', 'Communication'), ('teamwork', 'Teamwork'), ('leadership', 'Leadership'), ('compliance', 'Compliance & Discipline'), ('problem_solving', 'Problem Solving'), ('innovation', 'Innovation')], max_length=30)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('goal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='performance.goalcard')),
            ],
            options={
                'unique_together': {('goal_card', 'competency')},
            },
        ),
    ]
