# Generated by Django 6.0.5 on 2026-05-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_appraisal_template_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
