# Generated by Django 6.0.5 on 2026-05-30 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_free_text_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='achievement_description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='hr_comments',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='hr_rating',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='kpi_metric',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='manager_comments',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='manager_rating',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='self_comments',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='self_completion_pct',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='self_rating',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='weightage',
        ),
        migrations.RemoveField(
            model_name='goalprogressupdate',
            name='goal',
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(blank=True, max_length=200)),
                ('target_value', models.CharField(blank=True, max_length=200)),
                ('weightage', models.FloatField(default=0)),
                ('self_completion_pct', models.IntegerField(blank=True, null=True)),
                ('self_rating', models.IntegerField(blank=True, null=True)),
                ('self_comments', models.TextField(blank=True)),
                ('achievement_description', models.TextField(blank=True)),
                ('manager_rating', models.IntegerField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('hr_rating', models.IntegerField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.IntegerField(default=0)),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='performance.goal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='goalprogressupdate',
            name='kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='performance.kpi'),
        ),
    ]
