# Generated by Django 6.0.5 on 2026-06-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_remove_goal_achievement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcard',
            name='feedback_manager',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='feedback_organization',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='key_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='self_review_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='training_programs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='actual_achievement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kpi',
            name='data_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='kpi',
            name='frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kpi',
            name='manager_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='parameter_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kpi',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
