# Generated by Django 6.0.5 on 2026-06-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_appraisal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcard',
            name='manager_promoted',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='manager_promoted_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='manager_salary_correction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='manager_salary_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='manager_special_achievements',
            field=models.TextField(blank=True),
        ),
    ]
