# Generated by Django 6.0.5 on 2026-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_manager_remarks_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='hod_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='hod_promoted',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='hod_promoted_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='hod_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='hod_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='hod_salary_correction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='hod_salary_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='hod_special_achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user_type',
            field=models.CharField(choices=[('field_force', 'Field Force'), ('manager', 'Manager'), ('hod', 'HOD'), ('hr', 'HR Admin')], default='field_force', max_length=20),
        ),
        migrations.AlterField(
            model_name='goalcard',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('hr_approved', 'HR Approved'), ('finalized', 'Finalized')], default='draft', max_length=30),
        ),
    ]
