# Generated by Django 6.0.5 on 2026-06-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_kpi_hod_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcard',
            name='feedback_manager_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='feedback_organization_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
