# Generated by Django 6.0.5 on 2026-06-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_feedback_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcard',
            name='manager_suggested_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
