# Generated by Django 6.0.5 on 2026-06-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_manager_suggested_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcard',
            name='hod_competency_ratings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='manager_uplift_comments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='manager_uplift_ratings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
