# Generated by Django 6.0.5 on 2026-09-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_portaluser_hrms_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmssynclog',
            name='skipped_leavers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
