# Generated by Django 6.0.5 on 2026-09-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hrmssynclog_skipped_leavers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmssynclog',
            name='skipped_duplicate_email',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
