# Generated by Django 6.0.5 on 2026-09-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hrmssynclog_skipped_duplicate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
