# Generated by Django 5.2.17 on 2026-09-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_roompulse_app_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(db_index=True, max_length=150, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='orgtree/%Y/%m/')),
                ('updated_by_name', models.CharField(blank=True, max_length=200)),
                ('updated_by_email', models.CharField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['person_id'],
            },
        ),
        migrations.AddField(
            model_name='portaluser',
            name='can_edit_tree',
            field=models.BooleanField(default=False),
        ),
    ]
