# Generated by Django 6.0.5 on 2026-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_roompulse_app_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='office_mobile',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
