# Generated by Django 5.2.17 on 2026-09-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_treeprofile_portaluser_can_edit_tree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeprofile',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treeprofile',
            name='parent_hod_id',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
