# Generated by Django 5.2.17 on 2026-09-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_treeprofile_is_new_treeprofile_parent_hod_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeprofile',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
