# Generated by Django 5.2.17 on 2026-10-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_portaluser_grade_category_mobile'),
        ('accounts', '0010_treeprofile_is_hidden_alter_activitylog_id_and_more'),
    ]

    operations = [
    ]
