# Generated by Django 6.0.5 on 2026-10-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20261001_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
