# Generated by Django 6.0.5 on 2026-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_treeprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='can_manage_tree',
            field=models.BooleanField(default=False),
        ),
    ]
