# Generated by Django 6.0.5 on 2026-09-15 07:33

import django.db.models.deletion
import wall.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('submitted_by_name', models.CharField(blank=True, max_length=200)),
                ('submitted_by_email', models.CharField(blank=True, max_length=254)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Celebrations', 'Celebrations'), ('Team Moments', 'Team Moments'), ('CSR', 'CSR'), ('Events', 'Events'), ('Other', 'Other')], default='Other', max_length=40)),
                ('image', models.ImageField(upload_to=wall.models.photo_path)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviews', to='accounts.portaluser')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submissions', to='accounts.portaluser')),
            ],
            options={
                'verbose_name': 'wall photo',
                'ordering': ['-created_at'],
            },
        ),
    ]
