# Generated by Django 6.0.5 on 2026-09-15 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('submitted_by_name', models.CharField(blank=True, max_length=200)),
                ('submitted_by_email', models.CharField(blank=True, max_length=254)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=2000)),
                ('tone', models.CharField(choices=[('general', 'General'), ('maintenance', 'Maintenance / downtime'), ('update', 'Product or system update'), ('celebration', 'Celebration'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('announced_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviews', to='accounts.portaluser')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submissions', to='accounts.portaluser')),
            ],
            options={
                'ordering': ['-pinned', '-announced_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('National', 'National'), ('State', 'State')], default='State', max_length=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='noticeboard.holidayzone')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('zone', 'date', 'name'), name='one_holiday_per_zone_day')],
            },
        ),
    ]
