# Generated by Django 6.0.5 on 2026-09-24 09:50

import django.db.models.deletion
import django.utils.timezone
import noticeboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_roompulse_app_key'),
        ('noticeboard', '0002_seed_holiday_circular'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('submitted_by_name', models.CharField(blank=True, max_length=200)),
                ('submitted_by_email', models.CharField(blank=True, max_length=254)),
                ('reviewed_by_name', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=600)),
                ('category', models.CharField(choices=[('company', 'Company'), ('apis', 'APIs'), ('food_apis', 'Food APIs'), ('nutraceuticals', 'Nutraceuticals'), ('industry', 'Industry'), ('products', 'Products')], default='industry', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to=noticeboard.models.news_image_path)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviews', to='accounts.portaluser')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submissions', to='accounts.portaluser')),
            ],
            options={
                'ordering': ['-pinned', '-published_on', '-created_at'],
            },
        ),
    ]
