# Generated by Django 6.0.5 on 2026-09-24 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('google_news', 'Google News search'), ('rss', 'RSS / Atom feed')], default='google_news', max_length=20)),
                ('query', models.CharField(blank=True, max_length=300)),
                ('feed_url', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('company', 'Company'), ('apis', 'APIs'), ('food_apis', 'Food APIs'), ('nutraceuticals', 'Nutraceuticals'), ('industry', 'Industry'), ('products', 'Products')], default='industry', max_length=20)),
                ('auto_publish', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('max_per_run', models.PositiveSmallIntegerField(default=5)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('last_found', models.PositiveSmallIntegerField(default=0)),
                ('last_added', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='newsitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='source_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='noticeboard.newssource'),
        ),
    ]
