# Generated by Django 6.0.5 on 2026-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_newssource_newsitem_external_id_newsitem_source_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='max_age_days',
            field=models.PositiveSmallIntegerField(default=14),
        ),
    ]
