# Generated by Django 6.0.5 on 2026-09-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0006_seed_news_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
