# Generated by Django 6.0.5 on 2026-09-01 08:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('subzone', models.CharField(blank=True, max_length=100)),
                ('reporting_manager_id', models.CharField(blank=True, max_length=50)),
                ('hod_id', models.CharField(blank=True, max_length=50)),
                ('user_type', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hod', 'HOD'), ('admin', 'Admin')], default='employee', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Goal Setting Employee',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('fiscal_year', models.CharField(max_length=10)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('submission_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Goal Setting'), ('locked', 'Locked'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fiscal_year', '-created_at'],
                'unique_together': {('name', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='GoalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft with Employee'), ('submitted', 'Submitted - with Manager'), ('with_hod', 'With HOD'), ('awaiting_employee', 'Returned to Employee for Acceptance'), ('accepted', 'Accepted - Goals Agreed'), ('returned', 'Sent Back for Changes')], default='draft', max_length=30)),
                ('employee_note', models.TextField(blank=True)),
                ('manager_note', models.TextField(blank=True)),
                ('hod_note', models.TextField(blank=True)),
                ('employee_acceptance_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_acted_at', models.DateTimeField(blank=True, null=True)),
                ('hod_acted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_plans', to='goalsetting.goalcycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_plans', to='goalsetting.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kras', to='goalsetting.goalplan')),
            ],
            options={
                'verbose_name': 'KRA',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoalKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(blank=True, max_length=500)),
                ('weightage', models.FloatField(default=0)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=200)),
                ('parameter_type', models.CharField(blank=True, max_length=200)),
                ('data_source', models.CharField(blank=True, max_length=500)),
                ('target_value', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='goalsetting.kra')),
            ],
            options={
                'verbose_name': 'KPI',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to='goalsetting.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=20)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='goalsetting.goalplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('actor_role', models.CharField(max_length=20)),
                ('actor_name', models.CharField(blank=True, max_length=200)),
                ('actor_employee_id', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(max_length=40)),
                ('note', models.TextField(blank=True)),
                ('kras', models.JSONField(default=list)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('total_weightage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='goalsetting.goalplan')),
            ],
            options={
                'ordering': ['version_no'],
                'unique_together': {('plan', 'version_no')},
            },
        ),
    ]
