"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# pyrefly: ignore [missing-import]
from dotenv import load_dotenv
import os
load_dotenv()
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-gfwvx)x*fapr(ql+s8-*^apd&7z+k8ce=959v$4y5je!_&y2ob')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'accounts',
    'user_management',
    'performance',
    'appraisal',
    'goalsetting',
    'eom',
    'pms',
    'tada',
    'sales',
    'roompulse',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    import dj_database_url
    DATABASES = {'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)}
elif os.getenv('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
            'OPTIONS': {'charset': 'utf8mb4'} if os.getenv('DB_ENGINE', 'django.db.backends.mysql') == 'django.db.backends.mysql' else {},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'True') == 'True'
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://103.205.66.45",
    *[o.strip() for o in os.getenv('CORS_EXTRA_ORIGINS', '').split(',') if o.strip()],
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}

# Email (Gmail SMTP) — set EMAIL_HOST_USER and EMAIL_HOST_PASSWORD in .env
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', '')

# ── Pocket HRMS ───────────────────────────────────────────────────────────────
# The company's hire-to-retire system, and the source of truth for who works
# here. The intranet portal syncs its employee directory from this rather than
# keeping a second copy that has to be re-uploaded by hand.
#
# The token is company-scoped and is a credential: keep it in .env, never in
# the repo. Ask Pocket HRMS support for the company token.
#
# Their staging documentation originally pointed at
# essapistaging.pockethrms.com:8343, which is firewalled from the office
# network. Their support corrected this (2026-09-03): the current staging
# host is https://pockethrmsnext.pockethrms.com. That is STAGING — nobody has
# yet confirmed with a working token whether production uses the same host or
# the default below, so don't assume one implies the other.
POCKET_HRMS_BASE_URL = os.getenv('POCKET_HRMS_BASE_URL', 'https://api.pockethrms.com')
POCKET_HRMS_TOKEN = os.getenv('POCKET_HRMS_TOKEN', '')

# The EmployeeFields header is not a shared vocabulary — it's whatever column
# names APIS's own Pocket HRMS admin configured under Cloud Portal > Settings
# > Configurations > Fields. accounts/services/hrms.py ships a guessed default
# list; once accounts.services.hrms.discover_fields() has been run against a
# real token and the actual names are known, set them here as a comma-
# separated list rather than editing code:
#   POCKET_HRMS_EMPLOYEE_FIELDS=Id,Code,Fname,Lname,OfficialEmail,...
POCKET_HRMS_EMPLOYEE_FIELDS = os.getenv('POCKET_HRMS_EMPLOYEE_FIELDS', '')

# Local development sign-in. When on, the portal will register any company
# address on first use and hand the sign-in code straight back in the response
# instead of emailing it — because a developer's machine has no SMTP
# credentials and no synced employee directory, so otherwise nobody but the
# bootstrap superadmin can sign in locally at all.
#
# Gated on its own variable rather than on DEBUG, deliberately: DEBUG above
# defaults to True when unset, so a server whose .env forgot the line would
# silently turn this on. This one is off unless someone writes it down, and it
# belongs only in a local .env — never on QA or PROD.
PORTAL_DEV_LOGIN = os.getenv('PORTAL_DEV_LOGIN', '') == '1'

# Dedicated sender for offer/appraisal letters — separate account from the one
# used for PMS login OTPs. Falls back to the shared account above if unset.
OFFER_LETTER_EMAIL_HOST_USER = os.getenv('OFFER_LETTER_EMAIL_HOST_USER') or EMAIL_HOST_USER
OFFER_LETTER_EMAIL_HOST_PASSWORD = os.getenv('OFFER_LETTER_EMAIL_HOST_PASSWORD') or EMAIL_HOST_PASSWORD