from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('subzone', models.CharField(blank=True, max_length=100)),
                ('reporting_manager_id', models.CharField(blank=True, max_length=50)),
                ('hod_id', models.CharField(blank=True, max_length=50)),
                ('user_type', models.CharField(choices=[('field_force', 'Field Force'), ('manager', 'Manager'), ('hod', 'HOD'), ('hr', 'HR Admin')], default='field_force', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appraisal Employee Profile',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('fiscal_year', models.CharField(max_length=10)),
                ('goal_setting_deadline', models.DateField()),
                ('review_start_date', models.DateField()),
                ('review_deadline', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('goal_setting', 'Goal Setting Open'), ('goals_locked', 'Goals Locked'), ('review_open', 'Review Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fiscal_year', 'quarter'],
                'unique_together': {('quarter', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='GoalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('manager_approved', 'Manager Approved'), ('manager_rejected', 'Manager Rejected'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('hr_approved', 'HR Approved'), ('finalized', 'Finalized')], default='draft', max_length=30)),
                ('manager_remarks', models.TextField(blank=True)),
                ('hr_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('self_review_answers', models.JSONField(blank=True, default=list)),
                ('key_skills', models.JSONField(blank=True, default=list)),
                ('training_programs', models.TextField(blank=True)),
                ('feedback_manager', models.TextField(blank=True)),
                ('feedback_manager_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback_organization', models.TextField(blank=True)),
                ('feedback_organization_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('manager_suggested_skills', models.JSONField(blank=True, default=list)),
                ('manager_special_achievements', models.TextField(blank=True)),
                ('manager_promoted', models.CharField(blank=True, max_length=10)),
                ('manager_promoted_justification', models.TextField(blank=True)),
                ('manager_salary_correction', models.TextField(blank=True)),
                ('manager_salary_justification', models.TextField(blank=True)),
                ('hod_remarks', models.TextField(blank=True)),
                ('hod_special_achievements', models.TextField(blank=True)),
                ('hod_promoted', models.CharField(blank=True, max_length=10)),
                ('hod_promoted_justification', models.TextField(blank=True)),
                ('hod_salary_correction', models.TextField(blank=True)),
                ('hod_salary_justification', models.TextField(blank=True)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_uplift_ratings', models.JSONField(blank=True, default=dict)),
                ('manager_uplift_comments', models.JSONField(blank=True, default=dict)),
                ('hod_competency_ratings', models.JSONField(blank=True, default=dict)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_cards', to='appraisal.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_cards', to='appraisal.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'cycle')},
            },
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to='appraisal.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='appraisal/evidence/')),
                ('employee_summary', models.TextField(blank=True)),
                ('key_achievements', models.TextField(blank=True)),
                ('challenges_faced', models.TextField(blank=True)),
                ('support_required', models.TextField(blank=True)),
                ('training_needs', models.TextField(blank=True)),
                ('career_aspirations', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('next_quarter_plans', models.TextField(blank=True)),
                ('overall_self_rating', models.IntegerField(blank=True, null=True)),
                ('manager_overall_rating', models.IntegerField(blank=True, null=True)),
                ('manager_review_comments', models.TextField(blank=True)),
                ('employee_strengths', models.TextField(blank=True)),
                ('areas_of_improvement', models.TextField(blank=True)),
                ('development_plan', models.TextField(blank=True)),
                ('promotion_recommendation', models.CharField(blank=True, max_length=100)),
                ('increment_recommendation', models.CharField(blank=True, max_length=100)),
                ('hr_final_rating', models.IntegerField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('functional_head_remarks', models.TextField(blank=True)),
                ('functional_head_rating', models.IntegerField(blank=True, null=True)),
                ('management_approval_remarks', models.TextField(blank=True)),
                ('management_approval_rating', models.IntegerField(blank=True, null=True)),
                ('final_weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('performance_band', models.CharField(blank=True, choices=[('outstanding', '🏆 Outstanding'), ('exceeds', '⭐ Exceeds Expectations'), ('meets', '✅ Meets Expectations'), ('below', '⚠️ Below Expectations'), ('poor', '❌ Needs Improvement')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted'), ('manager_reviewed', 'Manager Reviewed'), ('hr_finalized', 'HR Finalized'), ('published', 'Published')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hr_finalized_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('goal_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appraisal.goalcard')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('goal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='appraisal.goalcard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(blank=True, max_length=200)),
                ('target_value', models.CharField(blank=True, max_length=200)),
                ('weightage', models.FloatField(default=0)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('unit_of_measurement', models.CharField(blank=True, max_length=100)),
                ('parameter_type', models.CharField(blank=True, max_length=100)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('actual_achievement', models.CharField(blank=True, max_length=200)),
                ('manager_score', models.FloatField(blank=True, null=True)),
                ('self_completion_pct', models.IntegerField(blank=True, null=True)),
                ('self_rating', models.IntegerField(blank=True, null=True)),
                ('self_comments', models.TextField(blank=True)),
                ('achievement_description', models.TextField(blank=True)),
                ('manager_rating', models.IntegerField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True)),
                ('hod_score', models.FloatField(blank=True, null=True)),
                ('hr_rating', models.IntegerField(blank=True, null=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.IntegerField(default=0)),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='appraisal.goal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GoalProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_pct', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('ahead', 'Ahead of Schedule'), ('at_risk', 'At Risk'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='on_track', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('highlights', models.TextField(blank=True)),
                ('blockers', models.TextField(blank=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='appraisal.kpi')),
            ],
            options={
                'ordering': ['-update_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency', models.CharField(choices=[('ownership', 'Ownership & Accountability'), ('communication', 'Communication'), ('teamwork', 'Teamwork'), ('leadership', 'Leadership'), ('compliance', 'Compliance & Discipline'), ('problem_solving', 'Problem Solving'), ('innovation', 'Innovation')], max_length=30)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('manager_remarks', models.TextField(blank=True)),
                ('goal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='appraisal.goalcard')),
            ],
            options={
                'unique_together': {('goal_card', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(max_length=20)),
                ('actor_name', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='appraisal.goalcard')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
