# Generated by Django 6.0.5 on 2026-06-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcard',
            name='support_document',
            field=models.FileField(blank=True, null=True, upload_to='appraisal_docs/'),
        ),
        migrations.AddField(
            model_name='goalcard',
            name='support_document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
