# Generated by Django 6.0.5 on 2026-06-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0002_add_support_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='appraisal_docs/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('goal_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_documents', to='appraisal.goalcard')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
