# Generated by Django 6.0.5 on 2026-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0003_add_support_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='actual_achievement',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='data_source',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='metric',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='parameter_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='target_value',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
