# Generated by Django 6.0.5 on 2026-08-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0002_seed_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
