# Generated by Django 6.0.5 on 2026-08-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0003_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_name', models.CharField(max_length=200)),
                ('requested_by_email', models.EmailField(max_length=254)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('stationery', 'Stationery'), ('it_equipment', 'IT Equipment'), ('furniture', 'Furniture'), ('pantry', 'Pantry / Housekeeping'), ('printing', 'Printing / Stationery Print'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('needed_by', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.CharField(blank=True, max_length=300)),
                ('fulfilled_by', models.CharField(blank=True, max_length=200)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='roompulse_r_status_9e3d93_idx')],
            },
        ),
    ]
