# Generated by Django, trimmed by hand: `makemigrations` also proposed
# AlterField(id=AutoField) on every existing roompulse table (a W042
# BigAutoField-vs-AutoField nudge from DEFAULT_AUTO_FIELD, unrelated to this
# change) — dropped here since altering primary-key columns on tables
# already live on QA/Live is a needless, separate risk this feature doesn't
# need to take.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0004_resourcerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='scope',
            field=models.CharField(choices=[('admin', 'Admin'), ('it_support', 'IT Support')], default='admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('admin', 'Admin'), ('it_support', 'IT Support')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_name', models.CharField(max_length=200)),
                ('requested_by_email', models.EmailField(max_length=254)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('technical_issue', 'Technical Issue'), ('account_access', 'Account / Login Access'), ('bug_report', 'Bug Report'), ('feature_request', 'Feature Request'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('related_to', models.CharField(blank=True, max_length=100)),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('closed', 'Closed')], db_index=True, default='pending', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='roompulse_s_status_886543_idx')],
            },
        ),
    ]
