# Generated by Django, trimmed by hand: see 0005_it_support_and_tickets.py's
# header comment — `makemigrations` again proposed the same unrelated
# AlterField(id=AutoField) noise on every pre-existing table, dropped here
# for the same reason.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0005_it_support_and_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='attachment_names',
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='roompulse_tickets/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='roompulse.supportticket')),
            ],
        ),
    ]
