# Generated by Django, trimmed by hand: see 0005_it_support_and_tickets.py's
# header comment — the same unrelated AlterField(id=AutoField) noise on
# every pre-existing table was dropped here too.
#
# Moves "IT Equipment" from ResourceRequest's category choices (Admin's
# stationery/furniture domain) to SupportTicket's (IT Support's domain) —
# a choices-only change, so no data migration: any existing ResourceRequest
# row with category='it_equipment' keeps that raw value, it just won't be
# offered as a choice in new Admin Ticket forms any more.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0006_ticket_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='category',
            field=models.CharField(choices=[('stationery', 'Stationery'), ('furniture', 'Furniture'), ('pantry', 'Pantry / Housekeeping'), ('printing', 'Printing / Stationery Print'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('technical_issue', 'Technical Issue'), ('account_access', 'Account / Login Access'), ('it_equipment', 'IT Equipment'), ('bug_report', 'Bug Report'), ('feature_request', 'Feature Request'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
    ]
