# Generated by Django 6.0.5 on 2026-09-22 09:32

import django.db.models.deletion
from django.db import migrations, models


def seed_history(apps, schema_editor):
    """Give tickets that predate the history table the trail we can prove.

    Only what the row itself still evidences: it was created, and if it was
    reviewed, who did that and when. The steps in between were never recorded
    anywhere, so they are not invented here.
    """
    SupportTicket = apps.get_model('roompulse', 'SupportTicket')
    TicketEvent = apps.get_model('roompulse', 'TicketEvent')
    events = []
    for t in SupportTicket.objects.all().iterator():
        events.append(TicketEvent(
            ticket=t, action='created', from_status='', to_status='pending',
            actor_email=t.requested_by_email, actor_role='',
            remarks='Recorded before the history table existed.',
            created_at=t.created_at,
        ))
        if t.reviewed_at and t.status in ('approved', 'rejected', 'in_progress',
                                          'closed', 'cancelled'):
            events.append(TicketEvent(
                ticket=t, action=('approved' if t.status != 'rejected' else 'rejected'),
                from_status='pending', to_status=t.status,
                actor_email=t.reviewed_by, actor_role='',
                remarks=t.admin_remarks, created_at=t.reviewed_at,
            ))
    if events:
        TicketEvent.objects.bulk_create(events, batch_size=500)


def drop_history(apps, schema_editor):
    apps.get_model('roompulse', 'TicketEvent').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0008_full_category_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='roompulse.supportticket'),
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('started', 'Work started'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='roompulse.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='roompulse_t_ticket__326af6_idx')],
            },
        ),
        migrations.RunPython(seed_history, drop_history),
    ]
