# Generated by Django 6.0.5 on 2026-09-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0009_ticket_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='release_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='released_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
