# Generated by Django 6.0.5 on 2026-09-24 06:23

from django.db import migrations, models


def backfill_who_did_the_work(apps, schema_editor):
    """Give tickets already closed the two facts the report needs.

    Without this the first monthly report is blank for everything done before
    today, which would read as "the team did nothing" rather than "we started
    counting on Tuesday". The closing entry in the ticket's history already
    says who closed it and when -- that IS the record; these columns only
    bring it somewhere a report can group by.
    """
    SupportTicket = apps.get_model('roompulse', 'SupportTicket')
    TicketEvent = apps.get_model('roompulse', 'TicketEvent')

    closings = {}
    for e in TicketEvent.objects.filter(action='closed').order_by('created_at'):
        closings[e.ticket_id] = e          # the last close wins

    for t in SupportTicket.objects.filter(status='closed'):
        e = closings.get(t.id)
        when = e.created_at if e else (t.reviewed_at or t.updated_at)
        who = (e.actor_email if e else t.reviewed_by) or ''
        t.performed_by_email = who[:254]
        t.performed_on = when.date() if when else None
        t.save(update_fields=['performed_by_email', 'performed_on'])


def unbackfill(apps, schema_editor):
    """Nothing to undo -- the fields go with the reverse of the AddFields."""


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0010_booking_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='logged_for',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='origin',
            field=models.CharField(choices=[('requested', 'Raised by someone'), ('logged', 'Logged by IT / Admin')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='performed_by_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='performed_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='performed_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='time_spent_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['performed_on', 'performed_by_email'], name='roompulse_s_perform_5568df_idx'),
        ),
        migrations.RunPython(backfill_who_did_the_work, unbackfill),
    ]
