# Generated by Django 6.0.5 on 2026-09-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0011_work_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('started', 'Work started'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('logged', 'Logged as done')], max_length=20),
        ),
    ]
