# Generated by Django 6.0.5 on 2026-09-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0012_logged_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='worked_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='worked_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
