# Generated by Django 6.0.5 on 2026-09-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0013_worked_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='source',
            field=models.CharField(choices=[('directory', 'Company directory'), ('manual', 'Added here')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
