# Generated by Django 6.0.5 on 2026-09-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0014_directory_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('account_login_access', 'Account / Login Access'), ('printer_scanner', 'Printer / Scanner'), ('vpn_access', 'VPN Access'), ('system_application_access', 'System / Application Access'), ('software_installation', 'Software Installation'), ('antivirus_security', 'Antivirus / Security'), ('microsoft_365', 'Microsoft 365'), ('teams_video_conferencing', 'Teams / Video Conferencing'), ('server_storage', 'Server / Storage'), ('database_access', 'Database Access'), ('mobile_device_support', 'Mobile / Device Support'), ('it_asset_request', 'IT Asset Request'), ('stationery_office_supplies', 'Stationery & Office Supplies'), ('housekeeping', 'Housekeeping'), ('pantry_refreshments', 'Pantry & Refreshments'), ('furniture_seating', 'Furniture & Seating'), ('facility_maintenance', 'Facility Maintenance'), ('electricity_lighting', 'Electricity & Lighting'), ('plumbing', 'Plumbing'), ('security_access', 'Security & Access'), ('id_card_employee_badge', 'ID Card / Employee Badge'), ('courier_dispatch', 'Courier & Dispatch'), ('travel_accommodation', 'Travel & Accommodation'), ('cab_transportation', 'Cab / Transportation'), ('meeting_room', 'Meeting Room'), ('office_equipment', 'Office Equipment'), ('printing_photocopy', 'Printing & Photocopy'), ('events_administration', 'Events & Administration'), ('vendor_service_request', 'Vendor / Service Request'), ('workplace_safety', 'Workplace Safety'), ('general_administration', 'General Administration'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
    ]
