# Generated by Django 6.0.5 on 2026-09-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0015_alter_supportticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='desk',
            field=models.CharField(choices=[('it', 'IT'), ('admin', 'Admin')], db_index=True, default='it', max_length=10),
        ),
    ]
