# Generated by Django 6.0.5 on 2026-09-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0017_backfill_desk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='assigned_to_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='assigned_to_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
