# Generated by Django 6.0.5 on 2026-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roompulse', '0019_booking_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('started', 'Work started'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('logged', 'Logged as done'), ('transferred', 'Passed to somebody else')], max_length=20),
        ),
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ticket', 'IT ticket'), ('item', 'Item request'), ('room', 'Room booking')], max_length=10)),
                ('object_id', models.PositiveIntegerField()),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=200)),
                ('by_email', models.EmailField(blank=True, max_length=254)),
                ('by_role', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['kind', 'object_id', 'created_at'], name='roompulse_h_kind_44a066_idx')],
            },
        ),
    ]
