# Generated by Django 5.2.17 on 2026-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('reporting_manager', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('New', 'New'), ('Replacement', 'Replacement')], default='New', max_length=20)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
