# Generated by Django 6.0.5 on 2026-09-15 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_activitylog'),
        ('vacancies', '0002_seed_hiring_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='review_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_reviews', to='accounts.portaluser'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='reviewed_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_submissions', to='accounts.portaluser'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='submitted_by_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='submitted_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
