# Generated by Django 6.0.5 on 2026-08-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('row_count', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(db_index=True)),
                ('period', models.DateField(db_index=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, db_index=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=100)),
                ('product_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=150)),
                ('sub_category', models.CharField(blank=True, max_length=150)),
                ('brand', models.CharField(blank=True, max_length=150)),
                ('pack_size', models.CharField(blank=True, max_length=80)),
                ('uom', models.CharField(blank=True, max_length=40)),
                ('channel', models.CharField(blank=True, db_index=True, max_length=100)),
                ('customer_code', models.CharField(blank=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('customer_type', models.CharField(blank=True, max_length=100)),
                ('salesperson', models.CharField(blank=True, db_index=True, max_length=200)),
                ('asm', models.CharField(blank=True, db_index=True, max_length=200)),
                ('rsm', models.CharField(blank=True, db_index=True, max_length=200)),
                ('territory', models.CharField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=18)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sales.salesupload')),
            ],
            options={
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['period', 'state'], name='sales_sales_period_1f8d81_idx'), models.Index(fields=['period', 'category'], name='sales_sales_period_f20caa_idx'), models.Index(fields=['period', 'salesperson'], name='sales_sales_period_e5758d_idx'), models.Index(fields=['period', 'channel'], name='sales_sales_period_5a1137_idx')],
            },
        ),
    ]
