# Generated by Django 6.0.5 on 2026-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='batch_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='business_type',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='currency_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='customer_district',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='customer_gst',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='customer_state_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='document_type',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='external_doc_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gross_weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gst_jurisdiction',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='is_return',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='item_alt_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='item_sub_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='line_amount_fc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='location_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='net_weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='packaging_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='packed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='posting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='prod_group',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='reason_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='remarks',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='retail_scheme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='sales_order_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='subzone',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='tcs_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='total_with_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='use_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='variant',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='warehouse_type',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='wholesale_scheme',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['is_cancelled', 'period'], name='sales_sales_is_canc_2b6f2f_idx'),
        ),
    ]
