# Generated by Django 6.0.5 on 2026-09-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesrecord_batch_no_salesrecord_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='sales_head',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='sfo_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='source',
            field=models.CharField(db_index=True, default='invoice', max_length=20),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['source', 'period'], name='sales_sales_source_60f768_idx'),
        ),
    ]
