# Generated by Django 6.0.5 on 2026-09-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesrecord_sales_head_salesrecord_sfo_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='plan_achievement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
