# Generated by Django 6.0.5 on 2026-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_tidy_upload_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesupload',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
