# Generated by Django 6.0.5 on 2026-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salesupload_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='line_type',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
