# Generated by Django 6.0.5 on 2026-09-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesrecord_is_not_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='gl_account_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='gl_account_no',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
