# Generated by Django 5.2.17 on 2026-10-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_person_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('sheet_name', models.CharField(blank=True, max_length=120)),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('as_of_month', models.DateField(blank=True, db_index=True, null=True)),
                ('as_of_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source_unit', models.CharField(blank=True, max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_snapshots', to='sales.salesupload')),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, db_index=True, max_length=60)),
                ('region', models.CharField(blank=True, db_index=True, max_length=60)),
                ('head_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('head_code', models.CharField(blank=True, db_index=True, max_length=60)),
                ('sfo_count', models.IntegerField(default=0)),
                ('lmtd', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('month_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('yesterday_billing', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mtd_primary', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mtd_secondary', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ytd_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ytd_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fy_target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fy_actual', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_total', models.BooleanField(db_index=True, default=False)),
                ('row_no', models.IntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sales.reviewsnapshot')),
            ],
            options={
                'ordering': ['row_no'],
                'indexes': [models.Index(fields=['snapshot', 'is_total'], name='sales_revie_snapsho_409ffb_idx')],
            },
        ),
    ]
