# Generated by Django 5.2.17 on 2026-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_review_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploaderGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('granted_by', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, default='head', max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('head_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('covers_all', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', 'name', 'email'],
                'constraints': [models.UniqueConstraint(fields=('email', 'role', 'head_key'), name='one_row_per_person_per_role')],
            },
        ),
    ]
